#ifndef __NETWORKLIB_CONFIG_HPP_INCLUDED_
#define __NETWORKLIB_CONFIG_HPP_INCLUDED_

#define MAX_BUFFER_LEN 8196
#define DEFAULT_READ_BUFF 1024
#define DEFAULT_WRITE_BUFF 1024

#define NL_AGAIN -3
#define NL_ERROR -100

#endif
